crypto_board/apps/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "accounts"
urlpatterns = [
    path("profile", views.ProfileView.as_view(), name="profile"),
    # path("signup", views.SignupView.as_view(), name="signup"),
    path("signup", views.signup, name="signup"),
    path("activate/<uidb64>/<token>", views.activate, name="activate"),
    # Django Auth
    path(
        "login",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path("logout", auth_views.LogoutView.as_view(), name="logout"),
]
# path('accounts/', include('django.contrib.auth.urls'))

crypto_board/apps/boards/urls.py
from django.urls import path

from . import views

app_name = "boards"
urlpatterns = [
    path("", views.index, name="index"),
    path("new", views.new, name="new"),
    path("<id>", views.show, name="show"),
    path("<id>/edit", views.edit, name="edit"),
    path("<id>/rename", views.rename, name="rename"),
    path("<id>/share/", views.share, name="share"),
    path("<board_user_id>/remove_board_user/", views.remove_board_user, name="remove_board_user"),
    path("<id>/versions/", views.versions, name="versions"),
    path("restore_version/<version_id>", views.restore_version, name="restore_version"),
]

crypto_board/apps/contact/urls.py
from django.urls import path

from .views import contact

app_name = "contact"
urlpatterns = [
    path("", contact, name="contact")
]

crypto_board/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("crypto_board.apps.public.urls")),
    path("accounts/", include("crypto_board.apps.accounts.urls")),
    path("boards/", include("crypto_board.apps.boards.urls")),
    path("contact/", include("crypto_board.apps.contact.urls")),
    path('tinymce/', include('tinymce.urls')),
]

crypto_board/apps/contact/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=100)
    message = models.TextField(max_length=1000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

crypto_board/apps/accounts/forms.py
from django import forms

class SignupForm(forms.Form):
    first_name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class' : 'form-control', 'id' : 'first_name', 'placeholder' : 'First Name', 'data-sb-validations' : 'required'}))
    last_name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class' : 'form-control', 'id' : 'last_name', 'placeholder' : 'Last Name', 'data-sb-validations' : 'required'}))
    username = forms.CharField(required=True, widget=forms.TextInput(attrs={'class' : 'form-control', 'id' : 'username', 'placeholder' : 'Username', 'data-sb-validations' : 'required'}))
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class' : 'form-control', 'id' : 'email', 'placeholder' : 'Email'}))
    password = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'class' : 'form-control', 'id' : 'password', 'placeholder' : 'Password', 'data-sb-validations' : 'required'}))
    confirm_password = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'class' : 'form-control', 'id' : 'confirm_password', 'placeholder' : 'Confirm Password', 'data-sb-validations' : 'required'}))

crypto_board/apps/boards/forms.py
from django import forms

class BoardForm(forms.Form):
    name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class' : 'form-control', 'id' : 'name', 'placeholder' : 'Name', 'data-sb-validations' : 'required'}))

crypto_board/apps/contact/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class' : 'form-control', 'id' : 'name', 'placeholder' : 'Name', 'data-sb-validations' : 'required'}))
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class' : 'form-control', 'id' : 'email', 'placeholder' : 'Email'}))
    message = forms.CharField(required=True, widget=forms.Textarea(attrs={'class' : 'form-control', 'id' : 'message', 'placeholder' : 'Message', 'rows' : 5, 'style' : 'height: 10rem'}))

crypto_board/apps/accounts/views.py
import bleach
from django.contrib.auth import login
from django.core.mail import EmailMessage, send_mail
from django.shortcuts import redirect, render
from django.http import HttpRequest, HttpResponse
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.utils.encoding import force_bytes, force_text

from . tokens import generate_token
from . forms import SignupForm
from crypto_board import settings


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "accounts/profile.html"

def signup(request: HttpRequest) -> HttpResponse:
    if request.method == 'GET':
        form = SignupForm()
    elif request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            username = bleach.clean(form.cleaned_data["username"])
            first_name = bleach.clean(form.cleaned_data["first_name"])
            last_name = bleach.clean(form.cleaned_data["last_name"])
            email = bleach.clean(form.cleaned_data["email"])
            password = bleach.clean(form.cleaned_data["password"])
            confirm_password = bleach.clean(form.cleaned_data["confirm_password"])

            if User.objects.filter(username = username):
                messages.error(request, 'Username already taken! Please try another username')

            if User.objects.filter(email = email):
                messages.error(request, 'Email already registered!')

            if len(username) < 3:
                messages.error(request, 'Username must be at least 3 character long!')

            if password != confirm_password:
                messages.error(request, "Passwords don't match!")

            if not username.isalnum():
                messages.error(request, "Username must be alphanumeric!")

            if len(list(messages.get_messages(request))) > 0:
                return render(request, "accounts/signup.html", {"form": form})

            user = User.objects.create_user(username, email, password)
            user.first_name = first_name
            user.last_name = last_name
            user.is_active = False
            user.save()
            messages.success(request, "Your account has been successfully created. We have sent you a confirmation email. Please check to activate your account.")
            current_site = get_current_site(request)
            email_subject = "Welcome to CryptoBoard! Confirm Your Email"
            email_content = render_to_string('accounts/signup_email.html', {
                'first_name': first_name,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': generate_token.make_token(user)
            })
            email = EmailMessage(
                email_subject,
                email_content,
                settings.DEFAULT_FROM_EMAIL,
                [email]
            )
            email.fail_silently = True
            email.send()

            return redirect('accounts:login')
    else:
        raise NotImplementedError
    return render(request, "accounts/signup.html", {"form": form})

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and generate_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return redirect('public:index')
    else:
        return render(request, 'accounts/activation_failed.html')

crypto_board/apps/boards/views.py
import bleach
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from django.contrib.auth.models import User
from crypto_board.apps.boards.models import Board, BoardVersion, BoardUser
from .forms import BoardForm
from crypto_board.apps.boards.custom_enc_dec import CustomEncDec

@login_required
def index(request):
    boards_ids = list(Board.objects.filter(owner_id = request.user.id).values_list('id', flat=True))
    boards_ids += list(BoardUser.objects.filter(user = request.user.id).values_list('board_id', flat=True))
    boards = Board.objects.filter(pk__in=boards_ids).order_by('-created_at')
    return render(request, "boards/index.html", {'boards': boards})

@login_required
def show(request, id):
    board = Board.objects.get(reference=id)
    board_users = list(BoardUser.objects.filter(board_id=board.id).values_list('user_id', flat=True))
    if request.user.id in board_users:
        return render(request, "boards/show.html", {'board': board, 'can_write': board.can_write(request.user.id)})
    else:
        messages.error(request, "You don't have permission to access this board!")
        return render(request, "boards/index.html")

@login_required
def new(request):
    if request.method == 'GET':
        form = BoardForm()
        return render(request, "boards/new.html", {'form': form})
    elif request.method == 'POST':
        form = BoardForm(request.POST)
        if form.is_valid():
            board = Board(owner=request.user)
            board.set_reference_number()
            custom_enc_dec = CustomEncDec()
            enc_name = custom_enc_dec.encrypt(bleach.clean(form.cleaned_data["name"]), board.reference)
            board.name = enc_name
            board.save()
            board_user = BoardUser(user=request.user, permission='owner', board=board)
            board_user.save()
            version = BoardVersion(name=enc_name, content="", board=board, modified_by=request.user)
            version.save()
            messages.success(request, "Board created successfully.")
            return redirect('boards:edit', id = board.reference)

@login_required
def edit(request, id):
    if request.method == 'GET':
        board = Board.objects.get(reference=id)
        board_users_ids = list(BoardUser.objects.filter(board_id=board.id).values_list('user_id', flat=True))
        if (request.user.id in board_users_ids) and (board.can_write(request.user.id)):
            version = BoardVersion.objects.filter(board_id=board.id).latest('id')
            return render(request, "boards/edit.html", {'board': board, 'version': version})
        else:
            messages.error(request, "You don't have permission to access this page!")
            return render(request, "boards/index.html")
    elif request.method == 'POST':
        custom_enc_dec = CustomEncDec()
        board = Board.objects.get(reference=id)
        enc_content = custom_enc_dec.encrypt(request.POST.get("content"), board.reference)
        previous_name = board.latest_name()
        previous_name = '' if (previous_name is None) else previous_name
        version = BoardVersion(name=previous_name, content=enc_content, board=board, modified_by=request.user)
        version.save()
        messages.success(request, f"Changes on the board saved successfully.")
        return redirect('boards:show', id = board.reference)

@login_required
def rename(request, id):
    board = Board.objects.get(reference=id)
    if request.method == 'GET':
        board_users_ids = list(BoardUser.objects.filter(board_id=board.id).values_list('user_id', flat=True))
        if (request.user.id in board_users_ids) and (board.can_write(request.user.id)):
            version = BoardVersion.objects.filter(board_id=board.id).latest('id')
            form = BoardForm()
            return render(request, "boards/rename.html", {'form': form, 'board': board, 'version': version})
        else:
            messages.error(request, "You don't have permission to access this page!")
            return render(request, "boards/index.html")
    elif request.method == 'POST':
        custom_enc_dec = CustomEncDec()
        enc_name = custom_enc_dec.encrypt(request.POST.get("name"), board.reference)
        previous_content = board.latest_content()
        previous_content = '' if (previous_content is None) else previous_content
        version = BoardVersion(name=enc_name, content=previous_content, board=board, modified_by=request.user)
        version.save()
        messages.success(request, f"Board renamed successfully.")
        return redirect('boards:show', id = board.reference)

@login_required
def share(request, id):
    if request.method == 'GET':
        board = Board.objects.get(reference=id)
        board_users = BoardUser.objects.filter(board_id=board.id)
        board_users_ids = list(BoardUser.objects.filter(board_id=board.id).values_list('user_id', flat=True))
        if (request.user.id in board_users_ids) and (board.can_write(request.user.id)):
            existing_user_ids = BoardUser.objects.filter(board_id=board.id).values_list('user_id', flat=True)
            data_for_options = User.objects.all().exclude(id__in=existing_user_ids).values_list('id', 'first_name', 'last_name')
            return render(request, "boards/share.html", {'board': board, 'data_for_options': data_for_options, 'board_users': board_users})
        else:
            messages.error(request, "You don't have permission to access this page!")
            return render(request, "boards/index.html")
    elif request.method == 'POST':
        board = Board.objects.get(reference=id)
        user_id = bleach.clean(request.POST.get("user_id"))
        user = User.objects.get(pk=user_id)
        permission = bleach.clean(request.POST.get("permission"))
        board_user = BoardUser(board=board, user_id=user_id, permission=permission)
        board_user.save()
        messages.success(request, f"Board shared with {user.get_full_name()} successfully.")
        return redirect('boards:share', id = board.reference)

@login_required
def remove_board_user(request, board_user_id):
    board_user = BoardUser.objects.get(pk=board_user_id)
    if request.user.id == board_user.board.owner_id:
        board_user.delete()
        messages.success(request, "User removed successfully from the board.")
    else:
        messages.error(request, "You don't have rights to remove a user!")
    return redirect('boards:share', id = board_user.board.reference)

@login_required
def versions(request, id):
    board = Board.objects.get(reference=id)
    board_users = list(BoardUser.objects.filter(board_id=board.id).values_list('user_id', flat=True))
    if (request.user.id in board_users) and (board.can_write(request.user.id)):
        versions = board.versions().order_by('-created_at')
        return render(request, "boards/versions.html", {'board': board, 'versions': versions})
    else:
        messages.error(request, "You don't have permission to access this page!")
        return render(request, "boards/index.html")

@login_required
def restore_version(request, version_id):
    version = BoardVersion.objects.get(pk=version_id)
    previous_name = version.board.latest_name()
    previous_name = '' if (previous_name is None) else previous_name
    new_version = BoardVersion(name=previous_name, content=version.content, board=version.board, modified_by=request.user)
    new_version.save()
    messages.success(request, "Board version restored successfully.")
    return redirect('boards:show', id = new_version.board.reference)

crypto_board/apps/contact/views.py
import bleach
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from django.core.mail import send_mail
from crypto_board.apps.contact.models import Contact

from crypto_board import settings

from .forms import ContactForm

def contact(request: HttpRequest) -> HttpResponse:
    if request.method == 'GET':
        form = ContactForm()
    elif request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = bleach.clean(form.cleaned_data["name"])
            email = bleach.clean(form.cleaned_data["email"])
            message = bleach.clean(form.cleaned_data["message"])
            contact = Contact(name=name, email=email, message=message)
            contact.save()
            send_mail(f"{name} sent an email | {email}", message, settings.DEFAULT_FROM_EMAIL, [settings.DEFAULT_FROM_EMAIL])
            return render(request, "contact.html", {"form": ContactForm(), "success": True})
    else:
        raise NotImplementedError
    return render(request, "contact.html", {"form": form})

crypto_board/views.py
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "accounts/profile.html"

crypto_board/templates/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock %}

{% block content %}
<br><br><br><br>
<h1 style="text-align: center;">CryptoBoard</h1>
<br>
<h4 style="text-align: center;"> Create, Edit and Share your secure boards hazzle free</h4>
<br><br>
<p style="text-align: center;">
  We provide the assurance of collaborating securely without the being concerned about the loss of data integrity or confidentiality<p>
    <p style="text-align: center;">
  Application uses security methods and encryption algorithms to ensure that only authorized personnel are able to access the boards</p>
  <p style="text-align: center;">
  We provide revision and version control feature so that boards are managed or can be retraced to any of the previous versions.</p>


{% endblock %}

crypto_board/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>{% block title %}CryptoBoard{% endblock %}</title>
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'theme/css/styles.css' %}" rel="stylesheet" />

    <link href="{% static 'css/main.css' %}" rel="stylesheet" />
    <link href="{% static 'tinymce/css/prism.css' %}" rel="stylesheet">
  </head>
  <body>
    {% include 'navbar.html' %}
    <main id="main">
      {% include 'messages.html' %}
      {% block content %}
      {% endblock %}
    </main>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <!-- Core theme JS-->
    <script src="{% static 'theme/js/scripts.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    <script src="{% static 'tinymce/js/prism.js' %}"></script>
    <script src="https://cdn.tiny.cloud/1/v02yb7tke149s9v8zubtijph2j1mzca3ykepacgjbk2mszkd/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script>
      tinymce.init({
        selector: '.richtext_content_field',
        plugins: 'print preview powerpaste casechange importcss tinydrive searchreplace autolink autosave save directionality advcode visualblocks visualchars fullscreen image link media mediaembed template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists checklist wordcount tinymcespellchecker a11ychecker imagetools textpattern noneditable help formatpainter permanentpen pageembed charmap tinycomments mentions quickbars linkchecker emoticons advtable blockquote',
        menubar: 'file edit view insert format tools table tc help',
        toolbar: 'undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | alignleft aligncenter alignright alignjustify | outdent indent |  numlist bullist checklist | forecolor backcolor casechange permanentpen formatpainter removeformat | pagebreak | charmap emoticons | fullscreen  preview save print | insertfile image media pageembed template link anchor codesample | a11ycheck ltr rtl | showcomments addcomment',
        autosave_ask_before_unload: true,
        autosave_interval: '30s',
        autosave_prefix: '{path}{query}-{id}-',
        autosave_restore_when_empty: false,
        autosave_retention: '2m',
        image_advtab: true,
        link_list: [
            {title: 'My page 1', value: 'https://www.tiny.cloud'},
            {title: 'My page 2', value: 'http://www.moxiecode.com'}
        ],
        image_list: [
            {title: 'My page 1', value: 'https://www.tiny.cloud'},
            {title: 'My page 2', value: 'http://www.moxiecode.com'}
        ],
        image_class_list: [
            {title: 'None', value: ''},
            {title: 'Some class', value: 'class-name'}
        ],
        importcss_append: true,
        templates: [
            {
                title: 'New Table',
                description: 'creates a new table',
                content: '<div class="mceTmpl"><table width="98%%"  border="0" cellspacing="0" cellpadding="0"><tr><th scope="col"> </th><th scope="col"> </th></tr><tr><td> </td><td> </td></tr></table></div>'
            },
            {title: 'Starting my story', description: 'A cure for writers block', content: 'Once upon a time...'},
            {
                title: 'New list with dates',
                description: 'New List with dates',
                content: '<div class="mceTmpl"><span class="cdate">cdate</span><br /><span class="mdate">mdate</span><h2>My List</h2><ul><li></li><li></li></ul></div>'
            }
        ],
        template_cdate_format: '[Date Created (CDATE): %m/%d/%Y : %H:%M:%S]',
        template_mdate_format: '[Date Modified (MDATE): %m/%d/%Y : %H:%M:%S]',
        height: 600,
        image_caption: true,
        quickbars_selection_toolbar: 'bold italic | quicklink h2 h3 blockquote quickimage quicktable',
        noneditable_noneditable_class: 'mceNonEditable',
        toolbar_mode: 'sliding',
        spellchecker_ignore_list: ['Ephox', 'Moxiecode'],
        tinycomments_mode: 'embedded',
        content_style: '.mymention{ color: gray; }',
        contextmenu: 'link image in',
        a11y_advanced_options: true,
        mentions_selector: '.mymention',
        mentions_item_type: 'profile'
      });
    </script>
  </body>
</html>

crypto_board/templates/boards.html
{% extends 'base.html' %}

{% block title %}BOARDS{% endblock %}

{% block content %}

<style>
  h1{
    text-align: center;
  }
 

  .container{
    width: 90%;
    display: grid;
    grid-template-columns: repeat(auto-fit,minmax(350px, 1fr));
    grid-gap: 20px;
  }

  .box{
    height: 200px;
    color: black;
    border: 2px solid red;
    position: relative;
  }
  a {
    font-size: 40px;
    color: black;
    display:flex;
    align-items: center;
    justify-content: center;
    }

  h2 {
    display:flex;
    align-items: center;
    justify-content: center;
    }
</style>
<h1> BOARDS</h1>
<div class="container">
  <div class="box">
    <a href="https://google.com">Board1</a>
    <h2>box1</h2>
  </div>
  <div class="box">
    <a href="https://google.com">Board2</a>
    <h2>box2</h2>
  </div>
  <div class="box">
    <a href="https://google.com">Board3</a>
    <h2>box3</h2>
  </div>
  <div class="box">
    <a href="https://google.com">Board4</a>
    <h2>box4</h2>
  </div>
  <div class="box">
    <a href="https://google.com">Board5</a>
    <h2>box5</h2>
  </div>
  <div class="box">
    <a href="https://google.com">Board6</a>
    <h2>box6</h2>
  </div>
  <div class="box">
    <a href="https://google.com">Board7</a>
    <h2>box7</h2>
  </div>
  <div class="box">
    <a href="https://google.com">Board8</a>
    <h2>box8</h2>
  </div>
  <div class="box">
    <a href="https://google.com">Board9</a>
    <h2>box9</h2>
  </div>
  <div class="box">
    <a href="https://google.com">Board10</a>
    <h2>box10</h2>
  </div>
</div>


{% endblock %}

crypto_board/templates/contact.html
{% extends 'base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
    <section class="page-section" id="contact">
        <div class="container">
            <!-- Contact Section Heading-->
            <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Contact Us</h2>
            <!-- Icon Divider-->
            <div class="divider-custom">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>
            <!-- Contact Section Form-->
            <div class="row justify-content-center">
                <div class="col-lg-8 col-xl-7">
                    {% if success %}
                        <div class="alert alert-success" role="alert">
                            Your message has been sent. We will revert to you soon.
                        </div>
                    {% endif %}
                    <form id="contactForm" name="sendMessage" novalidate="novalidate" method="post">
                        {% csrf_token %}

                        {% for field in form %}
                            <div class="form-floating mb-3">
                                {{ field }}
                                {{ field.label_tag }}
                                {% for error in field.errors %}
                                    <p class="help-block text-danger">{{error}}</p>
                                {% endfor %}
                            </div>
                        {% endfor %}
                        <!-- Submit Button-->
                        <button class="btn btn-primary btn-xl" id="submitButton" type="submit">Send</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

crypto_board/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
<!-- Masthead-->
<header class="masthead text-white text-center">
    <div class="container d-flex align-items-center flex-column">
        <!-- Masthead Avatar Image-->
        <img class="masthead-avatar mb-5" src="{% static 'img/cryptoboard_icon.png' %}" alt="..." />
        <!-- Masthead Heading-->
        <h1 class="masthead-heading text-uppercase mb-0">Future of secure collaboration</h1>
    </div>
</header>


{% endblock %}

crypto_board/templates/messages.html
<ul class="messages" id="messages-list">
    {% if messages %}
        {% for message in messages %}
        <li>
            {% if message.tags %}
                    <div class="alert alert-{{ message.tags }} msg fade show" role="alert">{{ message }}</div>
            {% else %}
                <div class="alert alert-info msg fade show" role="alert">{{ message }}</div>
            {% endif %}
        </li>
        {% endfor %}
    {% endif %}
</ul>

crypto_board/templates/navbar.html
{% url 'public:index' as index_url %}
{% url 'boards:index' as boards_url %}
{% url 'public:about' as about_url %}
{% url 'contact:contact' as contact_url %}
{% url 'accounts:profile' as profile_url %}
<nav class="navbar navbar-expand-lg bg-secondary text-uppercase" id="mainNav">
  <div class="container">
    <a class="navbar-brand" href="{{ index_url }}">CryptoBoard</a>
    <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded{% if request.path == boards_url %} active{% endif %}" href="{{ boards_url }}">Home</a></li>
        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded{% if request.path == about_url %} active{% endif %}" href="{{ about_url }}">About</a></li>
        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded{% if request.path == contact_url %} active{% endif %}" href="{{ contact_url }}">Contact</a></li>
        {% if user.is_authenticated %}
          <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded {% if request.path == profile_url %}active{% else %}{% endif %}" href="{{ profile_url }}">{{user.first_name}}</a>
          </li>
          <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded bg-danger" href="{% url 'accounts:logout' %}">Logout</a></li>
        {% else %}
          <li class="nav-item mx-0 mx-lg-1">
            <span><a class="nav-link py-3 px-0 px-lg-3 rounded bg-info" href="{% url 'accounts:login' %}">Login</a></span>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>