crypto_board/apps/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "accounts"
urlpatterns = [
    path("profile", views.ProfileView.as_view(), name="profile"),
    # path("signup", views.SignupView.as_view(), name="signup"),
    path("signup", views.signup, name="signup"),
    path("activate/<uidb64>/<token>", views.activate, name="activate"),
    # Django Auth
    path(
        "login",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path("logout", auth_views.LogoutView.as_view(), name="logout"),
]
# path('accounts/', include('django.contrib.auth.urls'))

crypto_board/apps/boards/urls.py
from django.urls import path

from . import views

app_name = "boards"
urlpatterns = [
    path("", views.index, name="index"),
    path("new", views.new, name="new"),
    path("<id>", views.show, name="show"),
    path("<id>/edit", views.edit, name="edit"),
    path("<id>/rename", views.rename, name="rename"),
    path("<id>/share/", views.share, name="share"),
    path("<board_user_id>/remove_board_user/", views.remove_board_user, name="remove_board_user"),
    path("<id>/versions/", views.versions, name="versions"),
    path("restore_version/<version_id>", views.restore_version, name="restore_version"),
]

crypto_board/apps/contact/urls.py
from django.urls import path

from .views import contact

app_name = "contact"
urlpatterns = [
    path("", contact, name="contact")
]

crypto_board/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("crypto_board.apps.public.urls")),
    path("accounts/", include("crypto_board.apps.accounts.urls")),
    path("boards/", include("crypto_board.apps.boards.urls")),
    path("contact/", include("crypto_board.apps.contact.urls")),
    path('tinymce/', include('tinymce.urls')),
]

crypto_board/apps/contact/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=100)
    message = models.TextField(max_length=1000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

crypto_board/apps/accounts/forms.py
from django import forms

class SignupForm(forms.Form):
    first_name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class' : 'form-control', 'id' : 'first_name', 'placeholder' : 'First Name', 'data-sb-validations' : 'required'}))
    last_name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class' : 'form-control', 'id' : 'last_name', 'placeholder' : 'Last Name', 'data-sb-validations' : 'required'}))
    username = forms.CharField(required=True, widget=forms.TextInput(attrs={'class' : 'form-control', 'id' : 'username', 'placeholder' : 'Username', 'data-sb-validations' : 'required'}))
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class' : 'form-control', 'id' : 'email', 'placeholder' : 'Email'}))
    password = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'class' : 'form-control', 'id' : 'password', 'placeholder' : 'Password', 'data-sb-validations' : 'required'}))
    confirm_password = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'class' : 'form-control', 'id' : 'confirm_password', 'placeholder' : 'Confirm Password', 'data-sb-validations' : 'required'}))

crypto_board/apps/boards/forms.py
from django import forms

class BoardForm(forms.Form):
    name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class' : 'form-control', 'id' : 'name', 'placeholder' : 'Name', 'data-sb-validations' : 'required'}))

crypto_board/apps/contact/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class' : 'form-control', 'id' : 'name', 'placeholder' : 'Name', 'data-sb-validations' : 'required'}))
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class' : 'form-control', 'id' : 'email', 'placeholder' : 'Email'}))
    message = forms.CharField(required=True, widget=forms.Textarea(attrs={'class' : 'form-control', 'id' : 'message', 'placeholder' : 'Message', 'rows' : 5, 'style' : 'height: 10rem'}))

crypto_board/apps/accounts/views.py
import bleach
from django.contrib.auth import login
from django.core.mail import EmailMessage, send_mail
from django.shortcuts import redirect, render
from django.http import HttpRequest, HttpResponse
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.utils.encoding import force_bytes, force_text

from . tokens import generate_token
from . forms import SignupForm
from crypto_board import settings


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "accounts/profile.html"

def signup(request: HttpRequest) -> HttpResponse:
    if request.method == 'GET':
        form = SignupForm()
    elif request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            username = bleach.clean(form.cleaned_data["username"])
            first_name = bleach.clean(form.cleaned_data["first_name"])
            last_name = bleach.clean(form.cleaned_data["last_name"])
            email = bleach.clean(form.cleaned_data["email"])
            password = bleach.clean(form.cleaned_data["password"])
            confirm_password = bleach.clean(form.cleaned_data["confirm_password"])

            if User.objects.filter(username = username):
                messages.error(request, 'Username already taken! Please try another username')

            if User.objects.filter(email = email):
                messages.error(request, 'Email already registered!')

            if len(username) < 3:
                messages.error(request, 'Username must be at least 3 character long!')

            if password != confirm_password:
                messages.error(request, "Passwords don't match!")

            if not username.isalnum():
                messages.error(request, "Username must be alphanumeric!")

            if len(list(messages.get_messages(request))) > 0:
                return render(request, "accounts/signup.html", {"form": form})

            user = User.objects.create_user(username, email, password)
            user.first_name = first_name
            user.last_name = last_name
            user.is_active = False
            user.save()
            messages.success(request, "Your account has been successfully created. We have sent you a confirmation email. Please check to activate your account.")
            current_site = get_current_site(request)
            email_subject = "Welcome to CryptoBoard! Confirm Your Email"
            email_content = render_to_string('accounts/signup_email.html', {
                'first_name': first_name,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': generate_token.make_token(user)
            })
            email = EmailMessage(
                email_subject,
                email_content,
                settings.DEFAULT_FROM_EMAIL,
                [email]
            )
            email.fail_silently = True
            email.send()

            return redirect('accounts:login')
    else:
        raise NotImplementedError
    return render(request, "accounts/signup.html", {"form": form})

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and generate_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return redirect('public:index')
    else:
        return render(request, 'accounts/activation_failed.html')

crypto_board/apps/boards/views.py
import bleach
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from django.contrib.auth.models import User
from crypto_board.apps.boards.models import Board, BoardVersion, BoardUser
from .forms import BoardForm
from crypto_board.apps.boards.custom_enc_dec import CustomEncDec

@login_required
def index(request):
    boards_ids = list(Board.objects.filter(owner_id = request.user.id).values_list('id', flat=True))
    boards_ids += list(BoardUser.objects.filter(user = request.user.id).values_list('board_id', flat=True))
    boards = Board.objects.filter(pk__in=boards_ids).order_by('-created_at')
    return render(request, "boards/index.html", {'boards': boards})

@login_required
def show(request, id):
    board = Board.objects.get(reference=id)
    board_users = list(BoardUser.objects.filter(board_id=board.id).values_list('user_id', flat=True))
    if request.user.id in board_users:
        return render(request, "boards/show.html", {'board': board, 'can_write': board.can_write(request.user.id)})
    else:
        messages.error(request, "You don't have permission to access this board!")
        return render(request, "boards/index.html")

@login_required
def new(request):
    if request.method == 'GET':
        form = BoardForm()
        return render(request, "boards/new.html", {'form': form})
    elif request.method == 'POST':
        form = BoardForm(request.POST)
        if form.is_valid():
            board = Board(owner=request.user)
            board.set_reference_number()
            custom_enc_dec = CustomEncDec()
            enc_name = custom_enc_dec.encrypt(bleach.clean(form.cleaned_data["name"]), board.reference)
            board.name = enc_name
            board.save()
            board_user = BoardUser(user=request.user, permission='owner', board=board)
            board_user.save()
            version = BoardVersion(name=enc_name, content="", board=board, modified_by=request.user)
            version.save()
            messages.success(request, "Board created successfully.")
            return redirect('boards:edit', id = board.reference)

@login_required
def edit(request, id):
    if request.method == 'GET':
        board = Board.objects.get(reference=id)
        board_users_ids = list(BoardUser.objects.filter(board_id=board.id).values_list('user_id', flat=True))
        if (request.user.id in board_users_ids) and (board.can_write(request.user.id)):
            version = BoardVersion.objects.filter(board_id=board.id).latest('id')
            return render(request, "boards/edit.html", {'board': board, 'version': version})
        else:
            messages.error(request, "You don't have permission to access this page!")
            return render(request, "boards/index.html")
    elif request.method == 'POST':
        custom_enc_dec = CustomEncDec()
        board = Board.objects.get(reference=id)
        enc_content = custom_enc_dec.encrypt(request.POST.get("content"), board.reference)
        previous_name = board.latest_name()
        previous_name = '' if (previous_name is None) else previous_name
        version = BoardVersion(name=previous_name, content=enc_content, board=board, modified_by=request.user)
        version.save()
        messages.success(request, f"Changes on the board saved successfully.")
        return redirect('boards:show', id = board.reference)

@login_required
def rename(request, id):
    board = Board.objects.get(reference=id)
    if request.method == 'GET':
        board_users_ids = list(BoardUser.objects.filter(board_id=board.id).values_list('user_id', flat=True))
        if (request.user.id in board_users_ids) and (board.can_write(request.user.id)):
            version = BoardVersion.objects.filter(board_id=board.id).latest('id')
            form = BoardForm()
            return render(request, "boards/rename.html", {'form': form, 'board': board, 'version': version})
        else:
            messages.error(request, "You don't have permission to access this page!")
            return render(request, "boards/index.html")
    elif request.method == 'POST':
        custom_enc_dec = CustomEncDec()
        enc_name = custom_enc_dec.encrypt(request.POST.get("name"), board.reference)
        previous_content = board.latest_content()
        previous_content = '' if (previous_content is None) else previous_content
        version = BoardVersion(name=enc_name, content=previous_content, board=board, modified_by=request.user)
        version.save()
        messages.success(request, f"Board renamed successfully.")
        return redirect('boards:show', id = board.reference)

@login_required
def share(request, id):
    if request.method == 'GET':
        board = Board.objects.get(reference=id)
        board_users = BoardUser.objects.filter(board_id=board.id)
        board_users_ids = list(BoardUser.objects.filter(board_id=board.id).values_list('user_id', flat=True))
        if (request.user.id in board_users_ids) and (board.can_write(request.user.id)):
            existing_user_ids = BoardUser.objects.filter(board_id=board.id).values_list('user_id', flat=True)
            data_for_options = User.objects.all().exclude(id__in=existing_user_ids).values_list('id', 'first_name', 'last_name')
            return render(request, "boards/share.html", {'board': board, 'data_for_options': data_for_options, 'board_users': board_users})
        else:
            messages.error(request, "You don't have permission to access this page!")
            return render(request, "boards/index.html")
    elif request.method == 'POST':
        board = Board.objects.get(reference=id)
        user_id = bleach.clean(request.POST.get("user_id"))
        user = User.objects.get(pk=user_id)
        permission = bleach.clean(request.POST.get("permission"))
        board_user = BoardUser(board=board, user_id=user_id, permission=permission)
        board_user.save()
        messages.success(request, f"Board shared with {user.get_full_name()} successfully.")
        return redirect('boards:share', id = board.reference)

@login_required
def remove_board_user(request, board_user_id):
    board_user = BoardUser.objects.get(pk=board_user_id)
    if request.user.id == board_user.board.owner_id:
        board_user.delete()
        messages.success(request, "User removed successfully from the board.")
    else:
        messages.error(request, "You don't have rights to remove a user!")
    return redirect('boards:share', id = board_user.board.reference)

@login_required
def versions(request, id):
    board = Board.objects.get(reference=id)
    board_users = list(BoardUser.objects.filter(board_id=board.id).values_list('user_id', flat=True))
    if (request.user.id in board_users) and (board.can_write(request.user.id)):
        versions = board.versions().order_by('-created_at')
        return render(request, "boards/versions.html", {'board': board, 'versions': versions})
    else:
        messages.error(request, "You don't have permission to access this page!")
        return render(request, "boards/index.html")

@login_required
def restore_version(request, version_id):
    version = BoardVersion.objects.get(pk=version_id)
    previous_name = version.board.latest_name()
    previous_name = '' if (previous_name is None) else previous_name
    new_version = BoardVersion(name=previous_name, content=version.content, board=version.board, modified_by=request.user)
    new_version.save()
    messages.success(request, "Board version restored successfully.")
    return redirect('boards:show', id = new_version.board.reference)

crypto_board/apps/contact/views.py
import bleach
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from django.core.mail import send_mail
from crypto_board.apps.contact.models import Contact

from crypto_board import settings

from .forms import ContactForm

def contact(request: HttpRequest) -> HttpResponse:
    if request.method == 'GET':
        form = ContactForm()
    elif request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = bleach.clean(form.cleaned_data["name"])
            email = bleach.clean(form.cleaned_data["email"])
            message = bleach.clean(form.cleaned_data["message"])
            contact = Contact(name=name, email=email, message=message)
            contact.save()
            send_mail(f"{name} sent an email | {email}", message, settings.DEFAULT_FROM_EMAIL, [settings.DEFAULT_FROM_EMAIL])
            return render(request, "contact.html", {"form": ContactForm(), "success": True})
    else:
        raise NotImplementedError
    return render(request, "contact.html", {"form": form})

crypto_board/views.py
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "accounts/profile.html"

crypto_board/templates/boards/edit.html
{% extends 'base.html' %}

{% block title %}Boards{% endblock %}

{% block content %}
<br>
<div class="row">
    <div class="col-md-10">
        <h1 style="text-align: center;">{{ board.decrypted_name }}</h1>
    </div>
    <div class="col-md-2">
        <a class="btn btn-primary" href="{% url 'boards:versions' id=board.reference %}">Previous Versions</a>
    </div>
</div>
<br>
<div class="container">
    <form id="boardForm" name="createBoardContent" novalidate="novalidate" method="post">
        {% csrf_token %}
        <div class="form-floating mb-3">
            <textarea class="richtext_content_field" name="content" data-sb-validations="required">
            {{ version.decrypted_content }}
            </textarea>
        </div>
        <div class="container-md text-center">
            <button class="btn btn-primary" id="submitButton" type="submit">Save</button>
            <a class="btn btn-secondary" href="{% url 'boards:show' id=board.reference %}">Discard</a>
        </div>
    </form>
</div>
{% endblock %}

crypto_board/templates/boards/index.html
{% extends 'base.html' %}

{% block title %}Boards{% endblock %}

{% block content %}
    <div class="container-md mt-3">
        <div class="row">
            <div class="col-md-10">
                <h1>My Boards</h1>
            </div>
            <div class="col-md-2">
                <a href="{% url 'boards:new' %}" class="btn btn-primary">Create board</a>
            </div>
        </div>

        <div class="row boards">
            {% for board in boards %}
                <div class="col-md-3">
                    <div class="card text-center">
                        <div class="content text-truncate" >
                            {{ board.decrypted_content|safe }}
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">{{ board.decrypted_name }}</h5>
                            <p class="card-text">{{ board.owner_name }}</p>
                            <a href="{% url 'boards:show' id=board.reference %}"> View</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

crypto_board/templates/boards/new.html
{% extends 'base.html' %}

{% block title %}Boards{% endblock %}

{% block content %}
    <section class="page-section" id="new-board">
        <div class="container">
            <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Create new board</h2>
            <div class="divider-custom">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>
            <div class="row justify-content-center">
                <div class="col-lg-8 col-xl-7">
                    <form id="boardForm" name="createBoard" novalidate="novalidate" method="post">
                        {% csrf_token %}

                        {% for field in form %}
                            <div class="form-floating mb-3">
                                {{ field }}
                                {{ field.label_tag }}
                                {% for error in field.errors %}
                                    <p class="help-block text-danger">{{error}}</p>
                                {% endfor %}
                            </div>
                        {% endfor %}
                        <button class="btn btn-primary btn-xl" id="submitButton" type="submit">Create</button>
                    </form>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

crypto_board/templates/boards/rename.html
{% extends 'base.html' %}

{% block title %}Boards{% endblock %}

{% block content %}
    <section class="page-section" id="new-board">
        <div class="container">
            <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Rename board</h2>
            <div class="divider-custom">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>
            <div class="row justify-content-center">
                <div class="col-lg-8 col-xl-7">
                    <form id="renameBoardForm" name="renameBoard" novalidate="novalidate" method="post">
                        {% csrf_token %}
                        <div class="form-floating mb-3">
                            <input type="text" class="form-control" name="name" data-sb-validations="required" value="{{ version.decrypted_name }}">
                        </div>
                        <div class="container-md text-center">
                            <button class="btn btn-primary" id="submitButton" type="submit">Update</button>
                            <a class="btn btn-secondary" href="{% url 'boards:show' id=board.reference %}">Discard</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

crypto_board/templates/boards/share.html
{% extends 'base.html' %}

{% block title %}Share Boards{% endblock %}

{% block content %}
    <section class="page-section" id="share-board">
        <div class="container">
            <div class="col-md-8 pull-left">
                <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Share with people</h2>
                <div class="divider-custom">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <div class="justify-content-center">
                    <form id="shareBoardForm" name="shareBoard" novalidate="novalidate" method="post">
                        {% csrf_token %}
                        <div class="form-floating mb-3">
                            <select name="user_id" id="user" class="form-control" data-sb-validations="required">
                                <option disabled selected> -- select a user -- </option>
                                {% for id, fname, lname in data_for_options %}
                                    <option value={{id}}>{{fname}} {{lname}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-floating mb-3">
                            <select name="permission" id="permission" class="form-control" data-sb-validations="required">
                                <option disabled selected> -- select a permission level -- </option>
                                <option value="read">Read</option>
                                <option value="write">Write</option>
                            </select>
                        </div>
                        <button class="btn btn-primary btn-xl" id="submitButton" type="submit">Share</button>
                    </form>
                </div>
            </div>
            <div class="col-md-4 pull-right">
                <div class="justify-content-center text-align-center">
                    <b>Shared with</b>
                    <ul>
                        {% for bu in board_users %}
                            <li>
                                {{ bu.user.get_full_name }} -
                                {{ bu.permission }}
                                {% if bu.permission != 'owner' and request.user.id == board.owner_id %}
                                    <a href="{% url 'boards:remove_board_user' board_user_id=bu.id %}">Remove</a>
                                {% endif %}
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

crypto_board/templates/boards/show.html
{% extends 'base.html' %}

{% block title %}Boards{% endblock %}

{% block content %}
    <h1 class="text-align-center">{{ board.decrypted_name }}</h1>
    <div class="container-md text-center">
      {% if can_write %}
        <a class="btn btn-primary" href="{% url 'boards:rename' id=board.reference %}">Rename</a>
        <a class="btn btn-success" href="{% url 'boards:edit' id=board.reference %}">Edit Content</a>
        <a class="btn btn-info" href="{% url 'boards:share' id=board.reference %}">Share</a>
      {% endif %}
      </div>
      <br><br>
      <div class="container square-box">
        <p>{{ board.decrypted_content|safe }}</p>
      </div>
{% endblock %}

crypto_board/templates/boards/versions.html
{% extends 'base.html' %}

{% block title %}Board Versions{% endblock %}

{% block content %}
  <div class="container-md">
    <br/>
    <h1 class="pull-left">{{ board.decrypted_name }} - Version History</h1>
    <div class="pull-right">
      <a class="btn btn-primary" href="{% url 'boards:show' id=board.reference %}"> Go back to board</a>
    </div>
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Version No.</th>
          <th scope="col">Modified By</th>
          <th scope="col">Modified At</th>
          <th scope="col">Name</th>
          <th scope="col">Content</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        {% for version in versions %}
          <tr>
            <td>{{ forloop.counter }}</th>
            <td>{{ version.modified_by_name }}</td>
            <td>{{ version.created_at }}</td>
            <td>{{ version.decrypted_name }}</td>
            <td>{% autoescape off %}{{ version.decrypted_content }}{% endautoescape %}</td>
            <td><a href="{% url 'boards:restore_version' version_id=version.id %}">RESTORE</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}